// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://obpgbqmajyyhzscxospo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9icGdicW1hanl5aHpzY3hvc3BvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwOTIzMzQsImV4cCI6MjA1OTY2ODMzNH0.dJJ06MSqKlj60QIlqE16aS9INzs7MIvNTWqXndX-fyg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);